travis:
  secure:
    BINSTAR_TOKEN: tzNfA3ccXnQ4Ch5xpD8z2x0hyw+/GKJ1Vnp9DXNU95HbFlve5unIGE1fTsCpysp46roycR7R4DgUap9qFk4MoKpE6bcU5vYgrkyH4EDLWRJHf+gtEN9Zl5eaft7TPHDs29EOYm+DRhejhg6F2gdQaglTVQ+vWQhFseOvVomeaXGVMT83W3LHlAhh73FBFcMDbQ/WjP8KdOiIbjhS+v8GIkEyWexHl7a3O+diWR0E2rPWYhRl/DrcKn6JPnH8nAbYVrzK7rV8sNos4JYyzkgAIRWrxu7RUTvKaVGnbbPSWxt1v7YeaOe+WQcBhx/lZcVc7GLc6Bt9GlizOo5h9Pz8evNCsqat4hZVimFS78jh1PIfjAUqefjoWqmstqUe7SG9nQ10ord2itpwfBG8y4F1epfFSrCJe1YWhaa2lPRB2gurPgxZ8IbPTQ1hHYqvc3LHfcYrGIL5xNYBONr/TEiuYIW0jBIwSjvcGMltg7s6w44rsFwAv4p8dDlc85V65GzS7xuGwLS3BnsGd7nYXRxSam8NHXG8jUM/ckJRA7eHUdLNgZxRmGljep8mnqEc5gx85hgEwSkL+F66BPI1fB85VqsK4sD2DppG9I2boItRlv9BpKURSW2Wpyr6b6uSHQIC+/iDbrfGJeAbkXXImC9MLqkcP93GVHYolkMQnK4voZo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
